<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="5" errors="1" failures="0" skip="0"><testcase classname="test_forms.TestRegistrationForm" name="test_registration_form_invalid" time="0.010"></testcase><testcase classname="test_forms.TestRegistrationForm" name="test_registration_form_valid" time="0.002"></testcase><testcase classname="test_models.UserTestCase" name="test_instance_username" time="0.005"></testcase><testcase classname="test_models.UserTestCase" name="test_instance_variable" time="0.002"></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="django.urls.exceptions.NoReverseMatch" message="Reverse for 'user' not found. 'user' is not a valid view function or pattern name."><![CDATA[Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/src/tests/test_views.py", line 98, in <module>
    class TestUserView(TestCase):
  File "/code/src/tests/test_views.py", line 99, in TestUserView
    url = reverse('user')
  File "/usr/local/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
]]></error></testcase></testsuite>